spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chenmmtest?serverTimezone=Asia/Shanghai
    username: chenmm
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
